package ru.itmo.hasd.lab1.model;

import lombok.Data;
import lombok.experimental.Accessors;

import java.util.List;
import java.util.Map;
import java.util.Set;

@Data
@Accessors(chain = true)
public class HeavyObject {

    private Long var1;
    private Long var2;
    private Long var3;
    private Long var4;
    private Long var5;
    private Long var6;
    private Long var7;
    private Long var8;
    private Long var9;
    private Long var10;
    private Long var11;
    private Long var12;
    private Long var13;
    private Long var14;
    private Long var15;
    private Long var16;
    private Long var17;
    private Long var18;
    private Long var19;
    private Long var20;
    private Long var21;
    private Long var22;
    private Long var23;
    private Long var24;
    private Long var25;

    private Integer var26;
    private Integer var27;
    private Integer var28;
    private Integer var29;
    private Integer var30;
    private Integer var31;
    private Integer var32;
    private Integer var33;
    private Integer var34;
    private Integer var35;
    private Integer var36;
    private Integer var37;
    private Integer var38;
    private Integer var39;
    private Integer var40;
    private Integer var41;
    private Integer var42;
    private Integer var43;
    private Integer var44;
    private Integer var45;
    private Integer var46;
    private Integer var47;
    private Integer var48;
    private Integer var49;
    private Integer var50;

    private Double var51;
    private Double var52;
    private Double var53;
    private Double var54;
    private Double var55;
    private Double var56;
    private Double var57;
    private Double var58;
    private Double var59;
    private Double var60;
    private Double var61;
    private Double var62;
    private Double var63;
    private Double var64;
    private Double var65;
    private Double var66;
    private Double var67;
    private Double var68;
    private Double var69;
    private Double var70;
    private Double var71;
    private Double var72;
    private Double var73;
    private Double var74;
    private Double var75;

    private Float var76;
    private Float var77;
    private Float var78;
    private Float var79;
    private Float var80;
    private Float var81;
    private Float var82;
    private Float var83;
    private Float var84;
    private Float var85;
    private Float var86;
    private Float var87;
    private Float var88;
    private Float var89;
    private Float var90;
    private Float var91;
    private Float var92;
    private Float var93;
    private Float var94;
    private Float var95;
    private Float var96;
    private Float var97;
    private Float var98;
    private Float var99;
    private Float var100;

    private String var101;
    private String var102;
    private String var103;
    private String var104;
    private String var105;
    private String var106;
    private String var107;
    private String var108;
    private String var109;
    private String var110;
    private String var111;
    private String var112;
    private String var113;
    private String var114;
    private String var115;
    private String var116;
    private String var117;
    private String var118;
    private String var119;
    private String var120;
    private String var121;
    private String var122;
    private String var123;
    private String var124;
    private String var125;

    private Character var126;
    private Character var127;
    private Character var128;
    private Character var129;
    private Character var130;
    private Character var131;
    private Character var132;
    private Character var133;
    private Character var134;
    private Character var135;
    private Character var136;
    private Character var137;
    private Character var138;
    private Character var139;
    private Character var140;
    private Character var141;
    private Character var142;
    private Character var143;
    private Character var144;
    private Character var145;
    private Character var146;
    private Character var147;
    private Character var148;
    private Character var149;
    private Character var150;

    private Boolean var151;
    private Boolean var152;
    private Boolean var153;
    private Boolean var154;
    private Boolean var155;
    private Boolean var156;
    private Boolean var157;
    private Boolean var158;
    private Boolean var159;
    private Boolean var160;
    private Boolean var161;
    private Boolean var162;
    private Boolean var163;
    private Boolean var164;
    private Boolean var165;
    private Boolean var166;
    private Boolean var167;
    private Boolean var168;
    private Boolean var169;
    private Boolean var170;
    private Boolean var171;
    private Boolean var172;
    private Boolean var173;
    private Boolean var174;
    private Boolean var175;

    private List<String> var176;
    private List<String> var177;
    private List<String> var178;
    private List<String> var179;
    private List<String> var180;
    private List<String> var181;
    private List<String> var182;
    private List<String> var183;
    private List<String> var184;
    private List<String> var185;
    private List<String> var186;
    private List<String> var187;
    private List<String> var188;
    private List<String> var189;
    private List<String> var190;
    private List<String> var191;
    private List<String> var192;
    private List<String> var193;
    private List<String> var194;
    private List<String> var195;
    private List<String> var196;
    private List<String> var197;
    private List<String> var198;
    private List<String> var199;
    private List<String> var200;

    private Set<Integer> var201;
    private Set<Integer> var202;
    private Set<Integer> var203;
    private Set<Integer> var204;
    private Set<Integer> var205;
    private Set<Integer> var206;
    private Set<Integer> var207;
    private Set<Integer> var208;
    private Set<Integer> var209;
    private Set<Integer> var210;
    private Set<Integer> var211;
    private Set<Integer> var212;
    private Set<Integer> var213;
    private Set<Integer> var214;
    private Set<Integer> var215;
    private Set<Integer> var216;
    private Set<Integer> var217;
    private Set<Integer> var218;
    private Set<Integer> var219;
    private Set<Integer> var220;
    private Set<Integer> var221;
    private Set<Integer> var222;
    private Set<Integer> var223;
    private Set<Integer> var224;
    private Set<Integer> var225;

    private Map<String, Long> var226;
    private Map<String, Long> var227;
    private Map<String, Long> var228;
    private Map<String, Long> var229;
    private Map<String, Long> var230;
    private Map<String, Long> var231;
    private Map<String, Long> var232;
    private Map<String, Long> var233;
    private Map<String, Long> var234;
    private Map<String, Long> var235;
    private Map<String, Long> var236;
    private Map<String, Long> var237;
    private Map<String, Long> var238;
    private Map<String, Long> var239;
    private Map<String, Long> var240;
    private Map<String, Long> var241;
    private Map<String, Long> var242;
    private Map<String, Long> var243;
    private Map<String, Long> var244;
    private Map<String, Long> var245;
    private Map<String, Long> var246;
    private Map<String, Long> var247;
    private Map<String, Long> var248;
    private Map<String, Long> var249;
    private Map<String, Long> var250;


}
