package ru.itmo.hasd.lab1.model;

import lombok.Data;
import lombok.experimental.Accessors;

import java.util.List;
import java.util.Map;
import java.util.Set;

@Data
@Accessors(chain = true)
public class MediumObject3 {

    private Long var1;
    private Long var2;
    private Long var3;
    private Long var4;
    private Long var5;
    private Long var6;
    private Long var7;
    private Long var8;
    private Long var9;
    private Long var10;
    private Long var11;
    private Long var12;
    private Long var13;
    private Long var14;
    private Long var15;
    private Long var16;
    private Long var17;
    private Long var18;
    private Long var19;
    private Long var20;

    private Integer var21;
    private Integer var22;
    private Integer var23;
    private Integer var24;
    private Integer var25;
    private Integer var26;
    private Integer var27;
    private Integer var28;
    private Integer var29;
    private Integer var30;
    private Integer var31;
    private Integer var32;
    private Integer var33;
    private Integer var34;
    private Integer var35;
    private Integer var36;
    private Integer var37;
    private Integer var38;
    private Integer var39;
    private Integer var40;

    private Double var41;
    private Double var42;
    private Double var43;
    private Double var44;
    private Double var45;
    private Double var46;
    private Double var47;
    private Double var48;
    private Double var49;
    private Double var50;
    private Double var51;
    private Double var52;
    private Double var53;
    private Double var54;
    private Double var55;
    private Double var56;
    private Double var57;
    private Double var58;
    private Double var59;
    private Double var60;

    private Float var61;
    private Float var62;
    private Float var63;
    private Float var64;
    private Float var65;
    private Float var66;
    private Float var67;
    private Float var68;
    private Float var69;
    private Float var70;
    private Float var71;
    private Float var72;
    private Float var73;
    private Float var74;
    private Float var75;
    private Float var76;
    private Float var77;
    private Float var78;
    private Float var79;
    private Float var80;

    private String var81;
    private String var82;
    private String var83;
    private String var84;
    private String var85;
    private String var86;
    private String var87;
    private String var88;
    private String var89;
    private String var90;
    private String var91;
    private String var92;
    private String var93;
    private String var94;
    private String var95;
    private String var96;
    private String var97;
    private String var98;
    private String var99;
    private String var100;

    private Character var101;
    private Character var102;
    private Character var103;
    private Character var104;
    private Character var105;
    private Character var106;
    private Character var107;
    private Character var108;
    private Character var109;
    private Character var110;
    private Character var111;
    private Character var112;
    private Character var113;
    private Character var114;
    private Character var115;
    private Character var116;
    private Character var117;
    private Character var118;
    private Character var119;
    private Character var120;

    private Boolean var121;
    private Boolean var122;
    private Boolean var123;
    private Boolean var124;
    private Boolean var125;
    private Boolean var126;
    private Boolean var127;
    private Boolean var128;
    private Boolean var129;
    private Boolean var130;
    private Boolean var131;
    private Boolean var132;
    private Boolean var133;
    private Boolean var134;
    private Boolean var135;
    private Boolean var136;
    private Boolean var137;
    private Boolean var138;
    private Boolean var139;
    private Boolean var140;

    private List<String> var141;
    private List<String> var142;
    private List<String> var143;
    private List<String> var144;
    private List<String> var145;
    private List<String> var146;
    private List<String> var147;
    private List<String> var148;
    private List<String> var149;
    private List<String> var150;
    private List<String> var151;
    private List<String> var152;
    private List<String> var153;
    private List<String> var154;
    private List<String> var155;
    private List<String> var156;
    private List<String> var157;
    private List<String> var158;
    private List<String> var159;
    private List<String> var160;

    private Set<Integer> var161;
    private Set<Integer> var162;
    private Set<Integer> var163;
    private Set<Integer> var164;
    private Set<Integer> var165;
    private Set<Integer> var166;
    private Set<Integer> var167;
    private Set<Integer> var168;
    private Set<Integer> var169;
    private Set<Integer> var170;
    private Set<Integer> var171;
    private Set<Integer> var172;
    private Set<Integer> var173;
    private Set<Integer> var174;
    private Set<Integer> var175;
    private Set<Integer> var176;
    private Set<Integer> var177;
    private Set<Integer> var178;
    private Set<Integer> var179;
    private Set<Integer> var180;

    private Map<String, Long> var181;
    private Map<String, Long> var182;
    private Map<String, Long> var183;
    private Map<String, Long> var184;
    private Map<String, Long> var185;
    private Map<String, Long> var186;
    private Map<String, Long> var187;
    private Map<String, Long> var188;
    private Map<String, Long> var189;
    private Map<String, Long> var190;
    private Map<String, Long> var191;
    private Map<String, Long> var192;
    private Map<String, Long> var193;
    private Map<String, Long> var194;
    private Map<String, Long> var195;
    private Map<String, Long> var196;
    private Map<String, Long> var197;
    private Map<String, Long> var198;
    private Map<String, Long> var199;
    private Map<String, Long> var200;

}
