version: '3'
services:
  spark-master:
    image: bitnami/spark:3.2.4
    environment:
      JDK_JAVA_OPTIONS: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
      SPARK_MODE: master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - "./spark-logs:/spark/logs"
      - "./data/Books_rating.csv:/Users/a.sashina/IdeaProjects/saving-compression-algorithms/data/Books_rating.csv"
      - "./data/books_data.csv:/Users/a.sashina/IdeaProjects/saving-compression-algorithms/data/books_data.csv"
      - "/tmp/spark:/tmp/spark"

  spark-worker-1:
    image: bitnami/spark:3.2.4
    depends_on:
      - spark-master
    environment:
      JDK_JAVA_OPTIONS: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - "./spark-logs:/spark/logs"
      - "./data/Books_rating.csv:/Users/a.sashina/IdeaProjects/saving-compression-algorithms/data/Books_rating.csv"
      - "./data/books_data.csv:/Users/a.sashina/IdeaProjects/saving-compression-algorithms/data/books_data.csv"
      - "/tmp/spark:/tmp/spark"

  spark-worker-2:
    image: bitnami/spark:3.2.4
    depends_on:
      - spark-master
    environment:
      JDK_JAVA_OPTIONS: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - "./spark-logs:/spark/logs"
      - "./data/Books_rating.csv:/Users/a.sashina/IdeaProjects/saving-compression-algorithms/data/Books_rating.csv"
      - "./data/books_data.csv:/Users/a.sashina/IdeaProjects/saving-compression-algorithms/data/books_data.csv"
      - "/tmp/spark:/tmp/spark"

  spark-worker-3:
    image: bitnami/spark:3.2.4
    depends_on:
      - spark-master
    environment:
      JDK_JAVA_OPTIONS: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - "./spark-logs:/spark/logs"
      - "./data/Books_rating.csv:/Users/a.sashina/IdeaProjects/saving-compression-algorithms/data/Books_rating.csv"
      - "./data/books_data.csv:/Users/a.sashina/IdeaProjects/saving-compression-algorithms/data/books_data.csv"
      - "/tmp/spark:/tmp/spark"

  redisdb:
    image: redis:7.4.1
    ports:
      - 6379:6379
    volumes:
      - redisdb_data:/data

volumes:
  redisdb_data: