package ru.itmo.hasd.model;

import lombok.Data;
import lombok.experimental.Accessors;

import java.util.List;
import java.util.Map;
import java.util.Set;

@Data
@Accessors(chain = true)
public class HeavyObject3 {

    private Long var1;
    private Long var2;
    private Long var3;
    private Long var4;
    private Long var5;
    private Long var6;
    private Long var7;
    private Long var8;
    private Long var9;
    private Long var10;
    private Long var11;
    private Long var12;
    private Long var13;
    private Long var14;
    private Long var15;
    private Long var16;
    private Long var17;
    private Long var18;
    private Long var19;
    private Long var20;
    private Long var21;
    private Long var22;
    private Long var23;
    private Long var24;
    private Long var25;
    private Long var26;
    private Long var27;
    private Long var28;
    private Long var29;
    private Long var30;
    private Long var31;
    private Long var32;
    private Long var33;
    private Long var34;
    private Long var35;
    private Long var36;
    private Long var37;
    private Long var38;
    private Long var39;
    private Long var40;
    private Long var41;
    private Long var42;
    private Long var43;
    private Long var44;
    private Long var45;
    private Long var46;
    private Long var47;
    private Long var48;
    private Long var49;
    private Long var50;

    private Integer var51;
    private Integer var52;
    private Integer var53;
    private Integer var54;
    private Integer var55;
    private Integer var56;
    private Integer var57;
    private Integer var58;
    private Integer var59;
    private Integer var60;
    private Integer var61;
    private Integer var62;
    private Integer var63;
    private Integer var64;
    private Integer var65;
    private Integer var66;
    private Integer var67;
    private Integer var68;
    private Integer var69;
    private Integer var70;
    private Integer var71;
    private Integer var72;
    private Integer var73;
    private Integer var74;
    private Integer var75;
    private Integer var76;
    private Integer var77;
    private Integer var78;
    private Integer var79;
    private Integer var80;
    private Integer var81;
    private Integer var82;
    private Integer var83;
    private Integer var84;
    private Integer var85;
    private Integer var86;
    private Integer var87;
    private Integer var88;
    private Integer var89;
    private Integer var90;
    private Integer var91;
    private Integer var92;
    private Integer var93;
    private Integer var94;
    private Integer var95;
    private Integer var96;
    private Integer var97;
    private Integer var98;
    private Integer var99;
    private Integer var100;

    private Double var101;
    private Double var102;
    private Double var103;
    private Double var104;
    private Double var105;
    private Double var106;
    private Double var107;
    private Double var108;
    private Double var109;
    private Double var110;
    private Double var111;
    private Double var112;
    private Double var113;
    private Double var114;
    private Double var115;
    private Double var116;
    private Double var117;
    private Double var118;
    private Double var119;
    private Double var120;
    private Double var121;
    private Double var122;
    private Double var123;
    private Double var124;
    private Double var125;
    private Double var126;
    private Double var127;
    private Double var128;
    private Double var129;
    private Double var130;
    private Double var131;
    private Double var132;
    private Double var133;
    private Double var134;
    private Double var135;
    private Double var136;
    private Double var137;
    private Double var138;
    private Double var139;
    private Double var140;
    private Double var141;
    private Double var142;
    private Double var143;
    private Double var144;
    private Double var145;
    private Double var146;
    private Double var147;
    private Double var148;
    private Double var149;
    private Double var150;

    private Float var151;
    private Float var152;
    private Float var153;
    private Float var154;
    private Float var155;
    private Float var156;
    private Float var157;
    private Float var158;
    private Float var159;
    private Float var160;
    private Float var161;
    private Float var162;
    private Float var163;
    private Float var164;
    private Float var165;
    private Float var166;
    private Float var167;
    private Float var168;
    private Float var169;
    private Float var170;
    private Float var171;
    private Float var172;
    private Float var173;
    private Float var174;
    private Float var175;
    private Float var176;
    private Float var177;
    private Float var178;
    private Float var179;
    private Float var180;
    private Float var181;
    private Float var182;
    private Float var183;
    private Float var184;
    private Float var185;
    private Float var186;
    private Float var187;
    private Float var188;
    private Float var189;
    private Float var190;
    private Float var191;
    private Float var192;
    private Float var193;
    private Float var194;
    private Float var195;
    private Float var196;
    private Float var197;
    private Float var198;
    private Float var199;
    private Float var200;

    private String var201;
    private String var202;
    private String var203;
    private String var204;
    private String var205;
    private String var206;
    private String var207;
    private String var208;
    private String var209;
    private String var210;
    private String var211;
    private String var212;
    private String var213;
    private String var214;
    private String var215;
    private String var216;
    private String var217;
    private String var218;
    private String var219;
    private String var220;
    private String var221;
    private String var222;
    private String var223;
    private String var224;
    private String var225;
    private String var226;
    private String var227;
    private String var228;
    private String var229;
    private String var230;
    private String var231;
    private String var232;
    private String var233;
    private String var234;
    private String var235;
    private String var236;
    private String var237;
    private String var238;
    private String var239;
    private String var240;
    private String var241;
    private String var242;
    private String var243;
    private String var244;
    private String var245;
    private String var246;
    private String var247;
    private String var248;
    private String var249;
    private String var250;

    private Character var251;
    private Character var252;
    private Character var253;
    private Character var254;
    private Character var255;
    private Character var256;
    private Character var257;
    private Character var258;
    private Character var259;
    private Character var260;
    private Character var261;
    private Character var262;
    private Character var263;
    private Character var264;
    private Character var265;
    private Character var266;
    private Character var267;
    private Character var268;
    private Character var269;
    private Character var270;
    private Character var271;
    private Character var272;
    private Character var273;
    private Character var274;
    private Character var275;
    private Character var276;
    private Character var277;
    private Character var278;
    private Character var279;
    private Character var280;
    private Character var281;
    private Character var282;
    private Character var283;
    private Character var284;
    private Character var285;
    private Character var286;
    private Character var287;
    private Character var288;
    private Character var289;
    private Character var290;
    private Character var291;
    private Character var292;
    private Character var293;
    private Character var294;
    private Character var295;
    private Character var296;
    private Character var297;
    private Character var298;
    private Character var299;
    private Character var300;

    private Boolean var301;
    private Boolean var302;
    private Boolean var303;
    private Boolean var304;
    private Boolean var305;
    private Boolean var306;
    private Boolean var307;
    private Boolean var308;
    private Boolean var309;
    private Boolean var310;
    private Boolean var311;
    private Boolean var312;
    private Boolean var313;
    private Boolean var314;
    private Boolean var315;
    private Boolean var316;
    private Boolean var317;
    private Boolean var318;
    private Boolean var319;
    private Boolean var320;
    private Boolean var321;
    private Boolean var322;
    private Boolean var323;
    private Boolean var324;
    private Boolean var325;
    private Boolean var326;
    private Boolean var327;
    private Boolean var328;
    private Boolean var329;
    private Boolean var330;
    private Boolean var331;
    private Boolean var332;
    private Boolean var333;
    private Boolean var334;
    private Boolean var335;
    private Boolean var336;
    private Boolean var337;
    private Boolean var338;
    private Boolean var339;
    private Boolean var340;
    private Boolean var341;
    private Boolean var342;
    private Boolean var343;
    private Boolean var344;
    private Boolean var345;
    private Boolean var346;
    private Boolean var347;
    private Boolean var348;
    private Boolean var349;
    private Boolean var350;

    private List<String> var351;
    private List<String> var352;
    private List<String> var353;
    private List<String> var354;
    private List<String> var355;
    private List<String> var356;
    private List<String> var357;
    private List<String> var358;
    private List<String> var359;
    private List<String> var360;
    private List<String> var361;
    private List<String> var362;
    private List<String> var363;
    private List<String> var364;
    private List<String> var365;
    private List<String> var366;
    private List<String> var367;
    private List<String> var368;
    private List<String> var369;
    private List<String> var370;
    private List<String> var371;
    private List<String> var372;
    private List<String> var373;
    private List<String> var374;
    private List<String> var375;
    private List<String> var376;
    private List<String> var377;
    private List<String> var378;
    private List<String> var379;
    private List<String> var380;
    private List<String> var381;
    private List<String> var382;
    private List<String> var383;
    private List<String> var384;
    private List<String> var385;
    private List<String> var386;
    private List<String> var387;
    private List<String> var388;
    private List<String> var389;
    private List<String> var390;
    private List<String> var391;
    private List<String> var392;
    private List<String> var393;
    private List<String> var394;
    private List<String> var395;
    private List<String> var396;
    private List<String> var397;
    private List<String> var398;
    private List<String> var399;
    private List<String> var400;

    private Set<Integer> var401;
    private Set<Integer> var402;
    private Set<Integer> var403;
    private Set<Integer> var404;
    private Set<Integer> var405;
    private Set<Integer> var406;
    private Set<Integer> var407;
    private Set<Integer> var408;
    private Set<Integer> var409;
    private Set<Integer> var410;
    private Set<Integer> var411;
    private Set<Integer> var412;
    private Set<Integer> var413;
    private Set<Integer> var414;
    private Set<Integer> var415;
    private Set<Integer> var416;
    private Set<Integer> var417;
    private Set<Integer> var418;
    private Set<Integer> var419;
    private Set<Integer> var420;
    private Set<Integer> var421;
    private Set<Integer> var422;
    private Set<Integer> var423;
    private Set<Integer> var424;
    private Set<Integer> var425;
    private Set<Integer> var426;
    private Set<Integer> var427;
    private Set<Integer> var428;
    private Set<Integer> var429;
    private Set<Integer> var430;
    private Set<Integer> var431;
    private Set<Integer> var432;
    private Set<Integer> var433;
    private Set<Integer> var434;
    private Set<Integer> var435;
    private Set<Integer> var436;
    private Set<Integer> var437;
    private Set<Integer> var438;
    private Set<Integer> var439;
    private Set<Integer> var440;
    private Set<Integer> var441;
    private Set<Integer> var442;
    private Set<Integer> var443;
    private Set<Integer> var444;
    private Set<Integer> var445;
    private Set<Integer> var446;
    private Set<Integer> var447;
    private Set<Integer> var448;
    private Set<Integer> var449;
    private Set<Integer> var450;

    private Map<String, Long> var451;
    private Map<String, Long> var452;
    private Map<String, Long> var453;
    private Map<String, Long> var454;
    private Map<String, Long> var455;
    private Map<String, Long> var456;
    private Map<String, Long> var457;
    private Map<String, Long> var458;
    private Map<String, Long> var459;
    private Map<String, Long> var460;
    private Map<String, Long> var461;
    private Map<String, Long> var462;
    private Map<String, Long> var463;
    private Map<String, Long> var464;
    private Map<String, Long> var465;
    private Map<String, Long> var466;
    private Map<String, Long> var467;
    private Map<String, Long> var468;
    private Map<String, Long> var469;
    private Map<String, Long> var470;
    private Map<String, Long> var471;
    private Map<String, Long> var472;
    private Map<String, Long> var473;
    private Map<String, Long> var474;
    private Map<String, Long> var475;
    private Map<String, Long> var476;
    private Map<String, Long> var477;
    private Map<String, Long> var478;
    private Map<String, Long> var479;
    private Map<String, Long> var480;
    private Map<String, Long> var481;
    private Map<String, Long> var482;
    private Map<String, Long> var483;
    private Map<String, Long> var484;
    private Map<String, Long> var485;
    private Map<String, Long> var486;
    private Map<String, Long> var487;
    private Map<String, Long> var488;
    private Map<String, Long> var489;
    private Map<String, Long> var490;
    private Map<String, Long> var491;
    private Map<String, Long> var492;
    private Map<String, Long> var493;
    private Map<String, Long> var494;
    private Map<String, Long> var495;
    private Map<String, Long> var496;
    private Map<String, Long> var497;
    private Map<String, Long> var498;
    private Map<String, Long> var499;
    private Map<String, Long> var500;

    private Long var501;
    private Long var502;
    private Long var503;
    private Long var504;
    private Long var505;
    private Long var506;
    private Long var507;
    private Long var508;
    private Long var509;
    private Long var510;
    private Long var511;
    private Long var512;
    private Long var513;
    private Long var514;
    private Long var515;
    private Long var516;
    private Long var517;
    private Long var518;
    private Long var519;
    private Long var520;
    private Long var521;
    private Long var522;
    private Long var523;
    private Long var524;
    private Long var525;
    private Long var526;
    private Long var527;
    private Long var528;
    private Long var529;
    private Long var530;
    private Long var531;
    private Long var532;
    private Long var533;
    private Long var534;
    private Long var535;
    private Long var536;
    private Long var537;
    private Long var538;
    private Long var539;
    private Long var540;
    private Long var541;
    private Long var542;
    private Long var543;
    private Long var544;
    private Long var545;
    private Long var546;
    private Long var547;
    private Long var548;
    private Long var549;
    private Long var550;

    private Integer var551;
    private Integer var552;
    private Integer var553;
    private Integer var554;
    private Integer var555;
    private Integer var556;
    private Integer var557;
    private Integer var558;
    private Integer var559;
    private Integer var560;
    private Integer var561;
    private Integer var562;
    private Integer var563;
    private Integer var564;
    private Integer var565;
    private Integer var566;
    private Integer var567;
    private Integer var568;
    private Integer var569;
    private Integer var570;
    private Integer var571;
    private Integer var572;
    private Integer var573;
    private Integer var574;
    private Integer var575;
    private Integer var576;
    private Integer var577;
    private Integer var578;
    private Integer var579;
    private Integer var580;
    private Integer var581;
    private Integer var582;
    private Integer var583;
    private Integer var584;
    private Integer var585;
    private Integer var586;
    private Integer var587;
    private Integer var588;
    private Integer var589;
    private Integer var590;
    private Integer var591;
    private Integer var592;
    private Integer var593;
    private Integer var594;
    private Integer var595;
    private Integer var596;
    private Integer var597;
    private Integer var598;
    private Integer var599;
    private Integer var600;

    private Double var601;
    private Double var602;
    private Double var603;
    private Double var604;
    private Double var605;
    private Double var606;
    private Double var607;
    private Double var608;
    private Double var609;
    private Double var610;
    private Double var611;
    private Double var612;
    private Double var613;
    private Double var614;
    private Double var615;
    private Double var616;
    private Double var617;
    private Double var618;
    private Double var619;
    private Double var620;
    private Double var621;
    private Double var622;
    private Double var623;
    private Double var624;
    private Double var625;
    private Double var626;
    private Double var627;
    private Double var628;
    private Double var629;
    private Double var630;
    private Double var631;
    private Double var632;
    private Double var633;
    private Double var634;
    private Double var635;
    private Double var636;
    private Double var637;
    private Double var638;
    private Double var639;
    private Double var640;
    private Double var641;
    private Double var642;
    private Double var643;
    private Double var644;
    private Double var645;
    private Double var646;
    private Double var647;
    private Double var648;
    private Double var649;
    private Double var650;

    private Float var651;
    private Float var652;
    private Float var653;
    private Float var654;
    private Float var655;
    private Float var656;
    private Float var657;
    private Float var658;
    private Float var659;
    private Float var660;
    private Float var661;
    private Float var662;
    private Float var663;
    private Float var664;
    private Float var665;
    private Float var666;
    private Float var667;
    private Float var668;
    private Float var669;
    private Float var670;
    private Float var671;
    private Float var672;
    private Float var673;
    private Float var674;
    private Float var675;
    private Float var676;
    private Float var677;
    private Float var678;
    private Float var679;
    private Float var680;
    private Float var681;
    private Float var682;
    private Float var683;
    private Float var684;
    private Float var685;
    private Float var686;
    private Float var687;
    private Float var688;
    private Float var689;
    private Float var690;
    private Float var691;
    private Float var692;
    private Float var693;
    private Float var694;
    private Float var695;
    private Float var696;
    private Float var697;
    private Float var698;
    private Float var699;
    private Float var700;

    private String var701;
    private String var702;
    private String var703;
    private String var704;
    private String var705;
    private String var706;
    private String var707;
    private String var708;
    private String var709;
    private String var710;
    private String var711;
    private String var712;
    private String var713;
    private String var714;
    private String var715;
    private String var716;
    private String var717;
    private String var718;
    private String var719;
    private String var720;
    private String var721;
    private String var722;
    private String var723;
    private String var724;
    private String var725;
    private String var726;
    private String var727;
    private String var728;
    private String var729;
    private String var730;
    private String var731;
    private String var732;
    private String var733;
    private String var734;
    private String var735;
    private String var736;
    private String var737;
    private String var738;
    private String var739;
    private String var740;
    private String var741;
    private String var742;
    private String var743;
    private String var744;
    private String var745;
    private String var746;
    private String var747;
    private String var748;
    private String var749;
    private String var750;

    private Character var751;
    private Character var752;
    private Character var753;
    private Character var754;
    private Character var755;
    private Character var756;
    private Character var757;
    private Character var758;
    private Character var759;
    private Character var760;
    private Character var761;
    private Character var762;
    private Character var763;
    private Character var764;
    private Character var765;
    private Character var766;
    private Character var767;
    private Character var768;
    private Character var769;
    private Character var770;
    private Character var771;
    private Character var772;
    private Character var773;
    private Character var774;
    private Character var775;
    private Character var776;
    private Character var777;
    private Character var778;
    private Character var779;
    private Character var780;
    private Character var781;
    private Character var782;
    private Character var783;
    private Character var784;
    private Character var785;
    private Character var786;
    private Character var787;
    private Character var788;
    private Character var789;
    private Character var790;
    private Character var791;
    private Character var792;
    private Character var793;
    private Character var794;
    private Character var795;
    private Character var796;
    private Character var797;
    private Character var798;
    private Character var799;
    private Character var800;

    private Boolean var801;
    private Boolean var802;
    private Boolean var803;
    private Boolean var804;
    private Boolean var805;
    private Boolean var806;
    private Boolean var807;
    private Boolean var808;
    private Boolean var809;
    private Boolean var810;
    private Boolean var811;
    private Boolean var812;
    private Boolean var813;
    private Boolean var814;
    private Boolean var815;
    private Boolean var816;
    private Boolean var817;
    private Boolean var818;
    private Boolean var819;
    private Boolean var820;
    private Boolean var821;
    private Boolean var822;
    private Boolean var823;
    private Boolean var824;
    private Boolean var825;
    private Boolean var826;
    private Boolean var827;
    private Boolean var828;
    private Boolean var829;
    private Boolean var830;
    private Boolean var831;
    private Boolean var832;
    private Boolean var833;
    private Boolean var834;
    private Boolean var835;
    private Boolean var836;
    private Boolean var837;
    private Boolean var838;
    private Boolean var839;
    private Boolean var840;
    private Boolean var841;
    private Boolean var842;
    private Boolean var843;
    private Boolean var844;
    private Boolean var845;
    private Boolean var846;
    private Boolean var847;
    private Boolean var848;
    private Boolean var849;
    private Boolean var850;

    private List<String> var851;
    private List<String> var852;
    private List<String> var853;
    private List<String> var854;
    private List<String> var855;
    private List<String> var856;
    private List<String> var857;
    private List<String> var858;
    private List<String> var859;
    private List<String> var860;
    private List<String> var861;
    private List<String> var862;
    private List<String> var863;
    private List<String> var864;
    private List<String> var865;
    private List<String> var866;
    private List<String> var867;
    private List<String> var868;
    private List<String> var869;
    private List<String> var870;
    private List<String> var871;
    private List<String> var872;
    private List<String> var873;
    private List<String> var874;
    private List<String> var875;
    private List<String> var876;
    private List<String> var877;
    private List<String> var878;
    private List<String> var879;
    private List<String> var880;
    private List<String> var881;
    private List<String> var882;
    private List<String> var883;
    private List<String> var884;
    private List<String> var885;
    private List<String> var886;
    private List<String> var887;
    private List<String> var888;
    private List<String> var889;
    private List<String> var890;
    private List<String> var891;
    private List<String> var892;
    private List<String> var893;
    private List<String> var894;
    private List<String> var895;
    private List<String> var896;
    private List<String> var897;
    private List<String> var898;
    private List<String> var899;
    private List<String> var900;

    private Set<Integer> var901;
    private Set<Integer> var902;
    private Set<Integer> var903;
    private Set<Integer> var904;
    private Set<Integer> var905;
    private Set<Integer> var906;
    private Set<Integer> var907;
    private Set<Integer> var908;
    private Set<Integer> var909;
    private Set<Integer> var910;
    private Set<Integer> var911;
    private Set<Integer> var912;
    private Set<Integer> var913;
    private Set<Integer> var914;
    private Set<Integer> var915;
    private Set<Integer> var916;
    private Set<Integer> var917;
    private Set<Integer> var918;
    private Set<Integer> var919;
    private Set<Integer> var920;
    private Set<Integer> var921;
    private Set<Integer> var922;
    private Set<Integer> var923;
    private Set<Integer> var924;
    private Set<Integer> var925;
    private Set<Integer> var926;
    private Set<Integer> var927;
    private Set<Integer> var928;
    private Set<Integer> var929;
    private Set<Integer> var930;
    private Set<Integer> var931;
    private Set<Integer> var932;
    private Set<Integer> var933;
    private Set<Integer> var934;
    private Set<Integer> var935;
    private Set<Integer> var936;
    private Set<Integer> var937;
    private Set<Integer> var938;
    private Set<Integer> var939;
    private Set<Integer> var940;
    private Set<Integer> var941;
    private Set<Integer> var942;
    private Set<Integer> var943;
    private Set<Integer> var944;
    private Set<Integer> var945;
    private Set<Integer> var946;
    private Set<Integer> var947;
    private Set<Integer> var948;
    private Set<Integer> var949;
    private Set<Integer> var950;

    private Map<String, Long> var951;
    private Map<String, Long> var952;
    private Map<String, Long> var953;
    private Map<String, Long> var954;
    private Map<String, Long> var955;
    private Map<String, Long> var956;
    private Map<String, Long> var957;
    private Map<String, Long> var958;
    private Map<String, Long> var959;
    private Map<String, Long> var960;
    private Map<String, Long> var961;
    private Map<String, Long> var962;
    private Map<String, Long> var963;
    private Map<String, Long> var964;
    private Map<String, Long> var965;
    private Map<String, Long> var966;
    private Map<String, Long> var967;
    private Map<String, Long> var968;
    private Map<String, Long> var969;
    private Map<String, Long> var970;
    private Map<String, Long> var971;
    private Map<String, Long> var972;
    private Map<String, Long> var973;
    private Map<String, Long> var974;
    private Map<String, Long> var975;
    private Map<String, Long> var976;
    private Map<String, Long> var977;
    private Map<String, Long> var978;
    private Map<String, Long> var979;
    private Map<String, Long> var980;
    private Map<String, Long> var981;
    private Map<String, Long> var982;
    private Map<String, Long> var983;
    private Map<String, Long> var984;
    private Map<String, Long> var985;
    private Map<String, Long> var986;
    private Map<String, Long> var987;
    private Map<String, Long> var988;
    private Map<String, Long> var989;
    private Map<String, Long> var990;
    private Map<String, Long> var991;
    private Map<String, Long> var992;
    private Map<String, Long> var993;
    private Map<String, Long> var994;
    private Map<String, Long> var995;
    private Map<String, Long> var996;
    private Map<String, Long> var997;
    private Map<String, Long> var998;
    private Map<String, Long> var999;
    private Map<String, Long> var1000;


}
