package ru.itmo.hasd.model;

import lombok.Data;
import lombok.experimental.Accessors;

import java.util.List;
import java.util.Map;
import java.util.Set;

@Data
@Accessors(chain = true)
public class HeavyObject2 {

    private Long var1;
    private Long var2;
    private Long var3;
    private Long var4;
    private Long var5;
    private Long var6;
    private Long var7;
    private Long var8;
    private Long var9;
    private Long var10;
    private Long var11;
    private Long var12;
    private Long var13;
    private Long var14;
    private Long var15;
    private Long var16;
    private Long var17;
    private Long var18;
    private Long var19;
    private Long var20;
    private Long var21;
    private Long var22;
    private Long var23;
    private Long var24;
    private Long var25;
    private Long var26;
    private Long var27;
    private Long var28;
    private Long var29;
    private Long var30;
    private Long var31;
    private Long var32;
    private Long var33;
    private Long var34;
    private Long var35;
    private Long var36;
    private Long var37;
    private Long var38;
    private Long var39;
    private Long var40;
    private Long var41;
    private Long var42;
    private Long var43;
    private Long var44;
    private Long var45;
    private Long var46;
    private Long var47;
    private Long var48;
    private Long var49;
    private Long var50;

    private Integer var51;
    private Integer var52;
    private Integer var53;
    private Integer var54;
    private Integer var55;
    private Integer var56;
    private Integer var57;
    private Integer var58;
    private Integer var59;
    private Integer var60;
    private Integer var61;
    private Integer var62;
    private Integer var63;
    private Integer var64;
    private Integer var65;
    private Integer var66;
    private Integer var67;
    private Integer var68;
    private Integer var69;
    private Integer var70;
    private Integer var71;
    private Integer var72;
    private Integer var73;
    private Integer var74;
    private Integer var75;
    private Integer var76;
    private Integer var77;
    private Integer var78;
    private Integer var79;
    private Integer var80;
    private Integer var81;
    private Integer var82;
    private Integer var83;
    private Integer var84;
    private Integer var85;
    private Integer var86;
    private Integer var87;
    private Integer var88;
    private Integer var89;
    private Integer var90;
    private Integer var91;
    private Integer var92;
    private Integer var93;
    private Integer var94;
    private Integer var95;
    private Integer var96;
    private Integer var97;
    private Integer var98;
    private Integer var99;
    private Integer var100;

    private Double var101;
    private Double var102;
    private Double var103;
    private Double var104;
    private Double var105;
    private Double var106;
    private Double var107;
    private Double var108;
    private Double var109;
    private Double var110;
    private Double var111;
    private Double var112;
    private Double var113;
    private Double var114;
    private Double var115;
    private Double var116;
    private Double var117;
    private Double var118;
    private Double var119;
    private Double var120;
    private Double var121;
    private Double var122;
    private Double var123;
    private Double var124;
    private Double var125;
    private Double var126;
    private Double var127;
    private Double var128;
    private Double var129;
    private Double var130;
    private Double var131;
    private Double var132;
    private Double var133;
    private Double var134;
    private Double var135;
    private Double var136;
    private Double var137;
    private Double var138;
    private Double var139;
    private Double var140;
    private Double var141;
    private Double var142;
    private Double var143;
    private Double var144;
    private Double var145;
    private Double var146;
    private Double var147;
    private Double var148;
    private Double var149;
    private Double var150;

    private Float var151;
    private Float var152;
    private Float var153;
    private Float var154;
    private Float var155;
    private Float var156;
    private Float var157;
    private Float var158;
    private Float var159;
    private Float var160;
    private Float var161;
    private Float var162;
    private Float var163;
    private Float var164;
    private Float var165;
    private Float var166;
    private Float var167;
    private Float var168;
    private Float var169;
    private Float var170;
    private Float var171;
    private Float var172;
    private Float var173;
    private Float var174;
    private Float var175;
    private Float var176;
    private Float var177;
    private Float var178;
    private Float var179;
    private Float var180;
    private Float var181;
    private Float var182;
    private Float var183;
    private Float var184;
    private Float var185;
    private Float var186;
    private Float var187;
    private Float var188;
    private Float var189;
    private Float var190;
    private Float var191;
    private Float var192;
    private Float var193;
    private Float var194;
    private Float var195;
    private Float var196;
    private Float var197;
    private Float var198;
    private Float var199;
    private Float var200;

    private String var201;
    private String var202;
    private String var203;
    private String var204;
    private String var205;
    private String var206;
    private String var207;
    private String var208;
    private String var209;
    private String var210;
    private String var211;
    private String var212;
    private String var213;
    private String var214;
    private String var215;
    private String var216;
    private String var217;
    private String var218;
    private String var219;
    private String var220;
    private String var221;
    private String var222;
    private String var223;
    private String var224;
    private String var225;
    private String var226;
    private String var227;
    private String var228;
    private String var229;
    private String var230;
    private String var231;
    private String var232;
    private String var233;
    private String var234;
    private String var235;
    private String var236;
    private String var237;
    private String var238;
    private String var239;
    private String var240;
    private String var241;
    private String var242;
    private String var243;
    private String var244;
    private String var245;
    private String var246;
    private String var247;
    private String var248;
    private String var249;
    private String var250;

    private Character var251;
    private Character var252;
    private Character var253;
    private Character var254;
    private Character var255;
    private Character var256;
    private Character var257;
    private Character var258;
    private Character var259;
    private Character var260;
    private Character var261;
    private Character var262;
    private Character var263;
    private Character var264;
    private Character var265;
    private Character var266;
    private Character var267;
    private Character var268;
    private Character var269;
    private Character var270;
    private Character var271;
    private Character var272;
    private Character var273;
    private Character var274;
    private Character var275;
    private Character var276;
    private Character var277;
    private Character var278;
    private Character var279;
    private Character var280;
    private Character var281;
    private Character var282;
    private Character var283;
    private Character var284;
    private Character var285;
    private Character var286;
    private Character var287;
    private Character var288;
    private Character var289;
    private Character var290;
    private Character var291;
    private Character var292;
    private Character var293;
    private Character var294;
    private Character var295;
    private Character var296;
    private Character var297;
    private Character var298;
    private Character var299;
    private Character var300;

    private Boolean var301;
    private Boolean var302;
    private Boolean var303;
    private Boolean var304;
    private Boolean var305;
    private Boolean var306;
    private Boolean var307;
    private Boolean var308;
    private Boolean var309;
    private Boolean var310;
    private Boolean var311;
    private Boolean var312;
    private Boolean var313;
    private Boolean var314;
    private Boolean var315;
    private Boolean var316;
    private Boolean var317;
    private Boolean var318;
    private Boolean var319;
    private Boolean var320;
    private Boolean var321;
    private Boolean var322;
    private Boolean var323;
    private Boolean var324;
    private Boolean var325;
    private Boolean var326;
    private Boolean var327;
    private Boolean var328;
    private Boolean var329;
    private Boolean var330;
    private Boolean var331;
    private Boolean var332;
    private Boolean var333;
    private Boolean var334;
    private Boolean var335;
    private Boolean var336;
    private Boolean var337;
    private Boolean var338;
    private Boolean var339;
    private Boolean var340;
    private Boolean var341;
    private Boolean var342;
    private Boolean var343;
    private Boolean var344;
    private Boolean var345;
    private Boolean var346;
    private Boolean var347;
    private Boolean var348;
    private Boolean var349;
    private Boolean var350;

    private List<String> var351;
    private List<String> var352;
    private List<String> var353;
    private List<String> var354;
    private List<String> var355;
    private List<String> var356;
    private List<String> var357;
    private List<String> var358;
    private List<String> var359;
    private List<String> var360;
    private List<String> var361;
    private List<String> var362;
    private List<String> var363;
    private List<String> var364;
    private List<String> var365;
    private List<String> var366;
    private List<String> var367;
    private List<String> var368;
    private List<String> var369;
    private List<String> var370;
    private List<String> var371;
    private List<String> var372;
    private List<String> var373;
    private List<String> var374;
    private List<String> var375;
    private List<String> var376;
    private List<String> var377;
    private List<String> var378;
    private List<String> var379;
    private List<String> var380;
    private List<String> var381;
    private List<String> var382;
    private List<String> var383;
    private List<String> var384;
    private List<String> var385;
    private List<String> var386;
    private List<String> var387;
    private List<String> var388;
    private List<String> var389;
    private List<String> var390;
    private List<String> var391;
    private List<String> var392;
    private List<String> var393;
    private List<String> var394;
    private List<String> var395;
    private List<String> var396;
    private List<String> var397;
    private List<String> var398;
    private List<String> var399;
    private List<String> var400;

    private Set<Integer> var401;
    private Set<Integer> var402;
    private Set<Integer> var403;
    private Set<Integer> var404;
    private Set<Integer> var405;
    private Set<Integer> var406;
    private Set<Integer> var407;
    private Set<Integer> var408;
    private Set<Integer> var409;
    private Set<Integer> var410;
    private Set<Integer> var411;
    private Set<Integer> var412;
    private Set<Integer> var413;
    private Set<Integer> var414;
    private Set<Integer> var415;
    private Set<Integer> var416;
    private Set<Integer> var417;
    private Set<Integer> var418;
    private Set<Integer> var419;
    private Set<Integer> var420;
    private Set<Integer> var421;
    private Set<Integer> var422;
    private Set<Integer> var423;
    private Set<Integer> var424;
    private Set<Integer> var425;
    private Set<Integer> var426;
    private Set<Integer> var427;
    private Set<Integer> var428;
    private Set<Integer> var429;
    private Set<Integer> var430;
    private Set<Integer> var431;
    private Set<Integer> var432;
    private Set<Integer> var433;
    private Set<Integer> var434;
    private Set<Integer> var435;
    private Set<Integer> var436;
    private Set<Integer> var437;
    private Set<Integer> var438;
    private Set<Integer> var439;
    private Set<Integer> var440;
    private Set<Integer> var441;
    private Set<Integer> var442;
    private Set<Integer> var443;
    private Set<Integer> var444;
    private Set<Integer> var445;
    private Set<Integer> var446;
    private Set<Integer> var447;
    private Set<Integer> var448;
    private Set<Integer> var449;
    private Set<Integer> var450;

    private Map<String, Long> var451;
    private Map<String, Long> var452;
    private Map<String, Long> var453;
    private Map<String, Long> var454;
    private Map<String, Long> var455;
    private Map<String, Long> var456;
    private Map<String, Long> var457;
    private Map<String, Long> var458;
    private Map<String, Long> var459;
    private Map<String, Long> var460;
    private Map<String, Long> var461;
    private Map<String, Long> var462;
    private Map<String, Long> var463;
    private Map<String, Long> var464;
    private Map<String, Long> var465;
    private Map<String, Long> var466;
    private Map<String, Long> var467;
    private Map<String, Long> var468;
    private Map<String, Long> var469;
    private Map<String, Long> var470;
    private Map<String, Long> var471;
    private Map<String, Long> var472;
    private Map<String, Long> var473;
    private Map<String, Long> var474;
    private Map<String, Long> var475;
    private Map<String, Long> var476;
    private Map<String, Long> var477;
    private Map<String, Long> var478;
    private Map<String, Long> var479;
    private Map<String, Long> var480;
    private Map<String, Long> var481;
    private Map<String, Long> var482;
    private Map<String, Long> var483;
    private Map<String, Long> var484;
    private Map<String, Long> var485;
    private Map<String, Long> var486;
    private Map<String, Long> var487;
    private Map<String, Long> var488;
    private Map<String, Long> var489;
    private Map<String, Long> var490;
    private Map<String, Long> var491;
    private Map<String, Long> var492;
    private Map<String, Long> var493;
    private Map<String, Long> var494;
    private Map<String, Long> var495;
    private Map<String, Long> var496;
    private Map<String, Long> var497;
    private Map<String, Long> var498;
    private Map<String, Long> var499;
    private Map<String, Long> var500;

}
